version: '3.7'

services:

  machinery-factory:
    restart: always
    build:
      context: ../machinery-factory
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      APP_ENV: ${APP_ENV}
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
    volumes:
      - ../machinery-factory:/var/www/machinery-factory:rw,cached

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - '80:80'
      - '443:433'
    depends_on:
      - machinery-factory
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro,cached
      - ../machinery-factory:/var/www/machinery-factory:ro,cached

  mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./mysql:/var/lib/mysql
